---
title: "gapminder-wrangle"
author: "guoRandall"
date: "2025-06-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
gapminder <- read_csv("data/gapminder.csv")
View(gapminder)
head(gapminder) # shows first 6
```
```{r}
tail(gapminder) # shows last 6
```

```{r}
str(gapminder)
```
```{r}
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
filter(gapminder, country %in% c("Mexico", "Peru"))
filter(gapminder, country == "Mexico", year == 2002)
```

```{r}
gap1 <- dplyr::select(gapminder, year, country, lifeExp)# choose column
gap2 <- dplyr::select(gapminder, year:lifeExp)
gap3 <- dplyr::select(gapminder, 1, 2, 4)# We can select columns with indices
gap4 <- dplyr::select(gapminder, -continent, -lifeExp)# don't want some column
```

```{r}
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- dplyr::select(gap_cambodia, -continent, -lifeExp)# easy to make mistake
#need new method
```

```{r}
gapminder |> head(3) #|> #cmd+shift+M #=head(gapminder, 3).
#"and then":take the gapminder data, and then give me the first three entries
```

```{r}
## instead of this...
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- dplyr::select(gap_cambodia, -continent, -lifeExp)
## ...we can do this
gap_cambodia <- gapminder |> filter(country == "Cambodia")
gap_cambodia2 <- gap_cambodia |> dplyr::select(-continent, -lifeExp)
## We can use the pipe to chain those two operations together:
gap_cambodia <- gapminder |>
filter(country == "Cambodia") |>
dplyr::select(-continent, -lifeExp)
```

```{r}
gapminder |>
  mutate(gdp = pop * gdpPercap)#create a new column named gdp.
```

```{r}
gapminder |>
  filter(year == 2002) |>
  group_by(continent) |>
  mutate(cont_pop = sum(pop))
```
```{r}
gapminder |>
  group_by(continent) |>
  summarize(cont_pop = sum(pop)) |>
  ungroup() # summarize() will actually only keep the columns that are grouped_by or summarized. So if we wanted to keep other columns, we’d have to do have a few more steps. ungroup() removes the grouping and it’s good to get in the habit of using it after a group_by().
```
```{r}
gapminder |>
  group_by(continent, year) |>
  summarize(cont_pop = sum(pop))
```

```{r}
gapminder |>
  group_by(continent, year) |>
  summarize(cont_pop = sum(pop)) |>
  arrange(year)
```
## How to make data tidy?
```{r}
## wide format
gap_wide <- readr::read_csv('data/gapminder_wide.csv')
gapminder <- readr::read_csv('data/gapminder.csv')
```
```{r}
head(gap_wide)
#str(gap_wide)
```
```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

